[tool.ruff]
line-length = 79
exclude = ['.venv', 'migrations']

[tool.isort]
profile = "black"
line_length = 79

[tool.taskipy.tasks]
lint = 'ruff . | blue --check . --diff'
format = 'blue . | isort .'
run = 'python main.py'
pre_test = 'task lint'
test = 'pytest -s -x --cov=. -vv'
post_test = 'coverage html'

[tool.pytest.ini_options]
pythonpath="D:\\development\\desafio-fullstack-visie\\backend"
markers = [
    "db: mark test as database",
    "main: mark test as main",
    "people: mark test as people",
]